### ISSUE TITLE
Make an effect that intuitively shows the push modifier is attached

### ISSUE THREAD

**Issue by ChrisD2012** [jasonsurratt/knockback-tickets#28]
**Describe the bug**
On the map with the houses and water all around, when I hit some enemies they slide for ages, it is really funny, but does not look right.

For example, I am the wizard and when I hit an enemy in the middle of the map he slides to the edge of the map, I have even had one slide out of the center of a house and down a hill.

**To Reproduce**
1. Go to the map with the houses and water all around
2. Start a wave
3. As the wizard kill a zombie and then keep shooting him till he slides off (have not tried with other heroes yet.)

**Expected behavior**
Slide, but perhaps not that far

**Screenshots**
Easy to replicate, did not include

**Reporter**
A reporter user name (e.g. steam name) no personal names.

**Comment by jasonsurratt** [comment]
The wizard's default weapon has modifiers that stick to the target and then apply a force away from the wizard. Stick a bunch to them and it is even funnier. There is also a modifier that pushes up instead of away. Hilarious when you stick it to a frying pan.

I should probably add an effect that shows the orb pushing. Maybe rings moving in the opposite direction?

**Comment by jasonsurratt** [comment]
Does this make it a little more intuitive? At low levels, there is a very subtle effect and very little force.

![PushModifier](https://user-images.githubusercontent.com/1638013/83656852-509a3580-a57d-11ea-8aaf-803c959beb47.gif)

At higher levels, it is a lot more in your face and a lot more force.

![PushModifierBig](https://user-images.githubusercontent.com/1638013/83656840-4c6e1800-a57d-11ea-9179-25016822c25c.gif)

**Comment by ChrisD2012** [comment]
Yes that looks awesome
